language: ruby
script: "bundle exec rake spec:coverage"
cache: bundler
env:
  global:
    - CODECOV_TOKEN="21653af2-874b-4597-942d-14ddc7c2f8fa"
before_install:
  - "gem update --system"
rvm:
  - 2.7.0
  - 2.6.0
  - 2.5.0
  - ruby-head
  - jruby
  - jruby-head
  - truffleruby
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: truffleruby
branches:
  only:
    - master
